routes:
  - slug: vergeletto-lago-dalzasca-lodano
    name: "Vergeletto – Lago d’Alzasca – Lodano"
    region: Tessin
    from: Vergeletto
    to: Lodano
    distance_km: 23.28
    ascent_m: 1862
    descent_m: 2420
    gpx: gpx/vergeletto-lago-dalzasca-lodano.gpx
    raw_gpx_url: https://raw.githubusercontent.com/mict-zhaw/hikes/main/gpx/vergeletto-lago-dalzasca-lodano.gpx
    swisstopo_url: https://swisstopo.app/u/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL21pY3Qtemhhdy9oaWtlcy9tYWluL2dweC92ZXJnZWxldHRvLWxhZ28tZGFsemFzY2EtbG9kYW5vLmdweA==
    notion_page_id: 3c32ae06-dc08-8107-8c12-f91048271912
